# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Carte' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

post_install do |installer|
    # 需要指定编译版本的第三方的名称
    myTargets = ['PasswordTextField', 'ChameleonFramework/Swift', 'SwiftRichString', 'AttributedLib']
    
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end

  # Pods for Carte
# Rx 系列
pod 'RxSwift'
pod 'RxCocoa'
pod 'ReactorKit'
pod 'RxGesture'

# UI
pod 'IGListKit', '~> 3.0'
pod 'SnapKit', '~> 4.0.0'
pod 'MJRefresh'
pod 'PasswordTextField'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'Onboard' # 引导页
pod 'ImagePicker'
pod 'ImageViewer'

# 动画
pod 'SkeletonView'
pod 'Hero'
pod 'ViewAnimator'
# pod 'pruce‘, '~> 1.0.0'
pod 'pop', '~> 1.0'
pod 'Gemini'

# AR
pod 'ARCL'

# 键盘
pod 'IQKeyboardManagerSwift'

# 手势
pod 'SJFullscreenPopGesture' #全局返回手势

# 网络框架
pod 'Alamofire', '~> 4.5'
pod 'Moya', '~> 10.0'
pod 'Kingfisher'
pod 'Unbox'
pod 'PromiseKit', '~> 4.4'

# 本地化
pod 'SwiftyUserDefaults'
pod 'Realm'

#图表
pod 'Charts'

# Extension
pod 'SwifterSwift'

# log
pod 'SwiftyBeaver'
#pod 'Dotzu'

# Lint
pod 'SwiftLint'

# Misc.
pod 'Then'
pod 'Reusable'

#工具
pod 'Reveal-SDK', '~> 4', :configurations => ['Debug']

# 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
pod 'React', :path => './ReactNative/node_modules/react-native', :subspecs => [
'Core',
'CxxBridge', # 如果RN版本 >= 0.45则加入此行
'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
'RCTText',
'RCTNetwork',
'RCTWebSocket', # 这个模块是用于调试功能的
# 在这里继续添加你所需要的RN模块
]
# 如果你的RN版本 >= 0.42.0，则加入下面这行。
pod 'yoga', :path => './ReactNative/node_modules/react-native/ReactCommon/yoga'
# 这里注意： 如果是0.49以下的RN，则使用下面这条：
# pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

# 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
pod 'DoubleConversion', :podspec => './ReactNative/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'GLog', :podspec => './ReactNative/node_modules/react-native/third-party-podspecs/GLog.podspec'
pod 'Folly', :podspec => './ReactNative/node_modules/react-native/third-party-podspecs/Folly.podspec'


  target 'CarteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarteUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
